server {
    host 127.0.0.1
    port 8080
    server_name localhost

    error_page 404 www/errors/404.html
    error_page 500 www/errors/500.html

    route / {
        methods GET HEAD
        root www
        index index.html
        directory_listing on
    }
}
