server {
    host        127.0.0.1
    port        8080 8081
    error_page  404 www/errors/404.html
    error_page  500 www/errors/500.html

    route / {
        methods         GET HEAD
        root            www
        directory_listing on
    }

    route /cgi-bin {
        methods         GET POST
        root            www
        cgi             .py /usr/bin/python3
    }
}